@echo off
:: Auto-generated by auto_model.py on 2026-03-27 15:27
:: Re-run:  python auto_model.py --rescan

set AXIOM_LLM_BACKEND=local_llama
set AXIOM_LLAMA_MODEL_PATH=D:\models\Qwen2.5-7B-Instruct-Q4_K_M.gguf
set AXIOM_LLM_CTX_WINDOW=4096
set AXIOM_LLM_MAX_TOKENS=512
